### ISSUE TITLE
CORS configuration for docker

### ISSUE THREAD

**Issue by Sparkobbable** [SoftwareArchitektur2/RideSchedulerBackend#12]

**Comment by Sparkobbable** [comment]
Wir haben drei Optionen:

1. (und beste Option) Wir finden eine Möglichkeit den Host des Frontends per Environment an die CORS Konfiguration des Backends zu geben
2. Wir bekommen es hin sämtliche CORS Zugriffe zuzulassen (auch redirect)
3. Wir geben statt des DNS-Name die tatsächliche IP des Dockers mit (muss dann im Network definiert werden)

**Comment by jpfrehe** [comment]
1. Ich habe noch zwei Wege dahin probiert, konnte aber leider noch nichts erfolgreiches finden.
2. Sehe ich für dieses Projekt als einfachste Lösung, finde dazu aber nichts
3. Habe ich versucht. Dann haben wir erstmal keine CORS Probleme, sondern das Frontend kann gar nicht mit dem Backend reden. Die requests bekommen alle nen timeout

**Comment by Sparkobbable** [comment]
Wir haben viiiieeel zu kompliziert gedacht ^^
Mir ist grade aufgefallen: React ist ja JavaScript, bzw. eine vollständig Client-seitige Technologie, heißt: Der Service Aufruf kommt IMMER direkt vom Browser (und nie vom Frontend-Host). Daher reicht der localhost...

Alternativ: Der Browser könnte den Frontend-Host (:80 bzw. :3000) aufrufen und dieser arbeitet mit einem Proxy fürs Backend, ist cleaner aber für dieses Projekt eigentlich too much

**Comment by jpfrehe** [comment]
Funktioniert jetzt mit env. variable auf localhost und wir sind happy
